// Copyright © 2026 Emma Flora Harbison & Luis Rey Sánchez
// SPDX-License-Identifier: Apache-2.0

import type { Locale } from "@/lib/i18n";

const COPY = {
  es: {
    title: "Consola",
    overview: "Resumen",
    learn: "Learn",
    forbiddenTitle: "Esta cuenta no abre la consola",
    forbiddenBody:
      "La consola solo está abierta para correos de la lista CONSOLE_EMAILS. Entra con una cuenta de correo y contraseña de esa lista. Una cuenta solo con frase no sirve.",
    statsIntro:
      "Conteos del host. No hay last_seen ni emails en claro. “Guardados en el host” es una escritura del vault cifrado, no que alguien abriera la app.",
    accountsTotal: "Cuentas",
    accountsNew7d: "Nuevas (7 días)",
    accountsNew30d: "Nuevas (30 días)",
    signups28d: "Altas por día (28 días, UTC)",
    emailAccounts: "Con correo",
    phraseOnly: "Solo frase",
    hostedDiaries: "Diarios hospedados",
    diariesSaved7d: "Guardados en el host (7 días)",
    diariesSaved30d: "Guardados en el host (30 días)",
    researchRows: "Filas del pool",
    researchNew30d: "Pool nuevas (30 días)",
    learnPublishedDb: "Learn publicados (DB)",
    learnDraftsDb: "Learn borradores (DB)",
    learnPublic: "Learn visibles en /learn",
    learnListTitle: "Artículos Learn",
    newArticle: "Artículo nuevo",
    statusPublished: "Publicado",
    statusDraft: "Borrador",
    originShipped: "En código",
    originDatabase: "En base de datos",
    saveDraft: "Guardar borrador",
    publish: "Publicar",
    deleteOverride: "Quitar fila de la base",
    deleteHint: "Si el artículo venía en código, vuelve a mostrarse el shipped. No borra el repositorio.",
    slug: "Slug",
    category: "Categoría",
    reviewedAt: "Revisado",
    sources: "Fuentes",
    sourceLabel: "Etiqueta",
    sourceHref: "URL",
    addSource: "Añadir fuente",
    addSection: "Añadir sección",
    remove: "Quitar",
    heading: "Título de sección",
    body: "Cuerpo",
    titleField: "Título",
    summary: "Resumen",
    notice: "Aviso",
    localeEs: "Español",
    localeEn: "English",
    saved: "Guardado",
    errorGeneric: "No se pudo guardar",
    publishBlocked: "Para publicar hace falta título, resumen, aviso y una sección en ES y EN, y al menos una fuente http(s).",
    backToList: "Volver a Learn",
    confirmDelete: "¿Quitar la fila de la base de datos?",
  },
  en: {
    title: "Console",
    overview: "Overview",
    learn: "Learn",
    forbiddenTitle: "This account cannot open the console",
    forbiddenBody:
      "The console is limited to emails in CONSOLE_EMAILS. Sign in with an email-and-password account on that list. A phrase-only account cannot match it.",
    statsIntro:
      "Host counts only. There is no last_seen and no plaintext email. “Saved on the host” means an encrypted vault write, not that someone opened the app.",
    accountsTotal: "Accounts",
    accountsNew7d: "New (7 days)",
    accountsNew30d: "New (30 days)",
    signups28d: "Sign-ups per day (28 days, UTC)",
    emailAccounts: "With email",
    phraseOnly: "Phrase only",
    hostedDiaries: "Hosted diaries",
    diariesSaved7d: "Saved on the host (7 days)",
    diariesSaved30d: "Saved on the host (30 days)",
    researchRows: "Research pool rows",
    researchNew30d: "Pool rows new (30 days)",
    learnPublishedDb: "Learn published (DB)",
    learnDraftsDb: "Learn drafts (DB)",
    learnPublic: "Learn visible on /learn",
    learnListTitle: "Learn articles",
    newArticle: "New article",
    statusPublished: "Published",
    statusDraft: "Draft",
    originShipped: "Shipped in code",
    originDatabase: "In the database",
    saveDraft: "Save draft",
    publish: "Publish",
    deleteOverride: "Remove database row",
    deleteHint: "If this slug shipped in code, the shipped article shows again. This does not delete the repository.",
    slug: "Slug",
    category: "Category",
    reviewedAt: "Reviewed",
    sources: "Sources",
    sourceLabel: "Label",
    sourceHref: "URL",
    addSource: "Add source",
    addSection: "Add section",
    remove: "Remove",
    heading: "Section heading",
    body: "Body",
    titleField: "Title",
    summary: "Summary",
    notice: "Notice",
    localeEs: "Spanish",
    localeEn: "English",
    saved: "Saved",
    errorGeneric: "Could not save",
    publishBlocked:
      "Publishing needs a title, summary, notice, and one section in ES and EN, plus at least one http(s) source.",
    backToList: "Back to Learn",
    confirmDelete: "Remove the database row?",
  },
} as const;

export type ConsoleCopy = (typeof COPY)[Locale];

export function consoleCopy(locale: Locale): ConsoleCopy {
  return COPY[locale];
}
